import numpy as np
from scipy.optimize import minimize

class AdaptiveMetaHeuristic:
    """
    An adaptive metaheuristic algorithm for solving black box optimization problems.
    
    The algorithm uses a combination of local search and gradient-based optimization to find the optimal solution.
    The strategy is refined based on the performance of the individual.
    
    Attributes:
    budget (int): The maximum number of function evaluations allowed.
    dim (int): The dimensionality of the search space.
    func (function): The black box function to optimize.
    search_space (list): The range of the search space.
    bounds (list): The bounds of the search space.
    adaptivity_threshold (float): The threshold for adapting the strategy.
    adaptivity_factor (float): The factor for adapting the strategy.
    """

    def __init__(self, budget, dim):
        """
        Initializes the AdaptiveMetaHeuristic algorithm.
        
        Args:
        budget (int): The maximum number of function evaluations allowed.
        dim (int): The dimensionality of the search space.
        """
        self.budget = budget
        self.dim = dim
        self.func = None
        self.search_space = None
        self.bounds = None
        self.adaptivity_threshold = 0.1
        self.adaptivity_factor = 0.5
        self.iterations = 0

    def __call__(self, func):
        """
        Optimizes the black box function using AdaptiveMetaHeuristic.
        
        Args:
        func (function): The black box function to optimize.
        
        Returns:
        tuple: A tuple containing the optimal solution and its cost.
        """
        if self.func is None:
            raise ValueError("The black box function must be initialized before calling this method.")
        
        # Initialize the search space
        self.search_space = [self.bounds] * self.dim
        self.bounds = [(-5.0, 5.0)] * self.dim
        
        # Initialize the optimal solution and its cost
        opt_solution = None
        opt_cost = float('inf')
        
        # Perform local search
        for _ in range(self.budget):
            # Generate a new solution by perturbing the current solution
            new_solution = self.perturb(self.search_space, self.bounds)
            
            # Evaluate the new solution using the black box function
            new_cost = self.func(new_solution)
            
            # Update the optimal solution and its cost if necessary
            if new_cost < opt_cost:
                opt_solution = new_solution
                opt_cost = new_cost
            
            # Refine the strategy based on the performance of the individual
            if self.iterations > 0 and self.iterations % self.adaptivity_threshold == 0:
                self.iterations += 1
                # Increase the adaptivity factor
                self.adaptivity_factor *= self.adaptivity_factor
                # Decrease the adaptivity threshold
                self.adaptivity_threshold *= self.adaptivity_factor
        
        # Return the optimal solution and its cost
        return opt_solution, opt_cost

    def perturb(self, search_space, bounds):
        """
        Generates a new solution by perturbing the current solution.
        
        Args:
        search_space (list): The current search space.
        bounds (list): The current bounds of the search space.
        
        Returns:
        list: A new solution generated by perturbing the current solution.
        """
        # Generate a new solution by randomly perturbing the current solution
        new_solution = [self.bounds[0] + np.random.uniform(-1, 1) * (self.bounds[1] - self.bounds[0]) for _ in range(self.dim)]
        
        # Ensure the new solution is within the bounds
        new_solution = [max(bounds[i], min(new_solution[i], bounds[i])) for i in range(self.dim)]
        
        return new_solution

# Description: Black Box Optimization using Adaptive MetaHeuristic Algorithm
# Code: 
# ```python
# Black Box Optimization using Adaptive MetaHeuristic Algorithm
# Code: 
# ```python
# ```python
# ```python
# # Initialize the AdaptiveMetaHeuristic algorithm
adaptive_metaheuristic = AdaptiveMetaHeuristic(budget=100, dim=10)

# Define a black box function
def func(x):
    return x[0]**2 + x[1]**2

# Optimize the black box function using the AdaptiveMetaHeuristic algorithm
opt_solution, opt_cost = adaptive_metaheuristic(func)

# Print the result
print("Optimal solution:", opt_solution)
print("Optimal cost:", opt_cost)