import numpy as np
from scipy.optimize import minimize

class MetaHeuristic:
    """
    A metaheuristic algorithm for solving black box optimization problems.
    
    The algorithm uses a combination of local search and gradient-based optimization to find the optimal solution.
    
    Attributes:
    budget (int): The maximum number of function evaluations allowed.
    dim (int): The dimensionality of the search space.
    func (function): The black box function to optimize.
    search_space (list): The range of the search space.
    bounds (list): The bounds of the search space.
    """

    def __init__(self, budget, dim):
        """
        Initializes the MetaHeuristic algorithm.
        
        Args:
        budget (int): The maximum number of function evaluations allowed.
        dim (int): The dimensionality of the search space.
        """
        self.budget = budget
        self.dim = dim
        self.func = None
        self.search_space = None
        self.bounds = None

    def __call__(self, func):
        """
        Optimizes the black box function using MetaHeuristic.
        
        Args:
        func (function): The black box function to optimize.
        
        Returns:
        tuple: A tuple containing the optimal solution and its cost.
        """
        if self.func is None:
            raise ValueError("The black box function must be initialized before calling this method.")
        
        # Initialize the search space
        self.search_space = [self.bounds] * self.dim
        self.bounds = [(-5.0, 5.0)] * self.dim
        
        # Initialize the optimal solution and its cost
        opt_solution = None
        opt_cost = float('inf')
        
        # Perform local search
        for _ in range(self.budget):
            # Generate a new solution by perturbing the current solution
            new_solution = self.perturb(self.search_space, self.bounds)
            
            # Evaluate the new solution using the black box function
            new_cost = self.func(new_solution)
            
            # Update the optimal solution and its cost if necessary
            if new_cost < opt_cost:
                opt_solution = new_solution
                opt_cost = new_cost
        
        # Return the optimal solution and its cost
        return opt_solution, opt_cost

    def perturb(self, search_space, bounds):
        """
        Generates a new solution by perturbing the current solution.
        
        Args:
        search_space (list): The current search space.
        bounds (list): The current bounds of the search space.
        
        Returns:
        list: A new solution generated by perturbing the current solution.
        """
        # Generate a new solution by randomly perturbing the current solution
        new_solution = [self.bounds[0] + np.random.uniform(-1, 1) * (self.bounds[1] - self.bounds[0]) for _ in range(self.dim)]
        
        # Ensure the new solution is within the bounds
        new_solution = [max(bounds[i], min(new_solution[i], bounds[i])) for i in range(self.dim)]
        
        return new_solution

    def adaptive_perturb(self, individual, bounds, alpha=0.1):
        """
        Refines the adaptive perturbation strategy.
        
        Args:
        individual (list): The current individual.
        bounds (list): The current bounds of the search space.
        alpha (float, optional): The perturbation strength. Defaults to 0.1.
        """
        # Evaluate the individual using the black box function
        new_individual = self.evaluate_fitness(individual)
        
        # Refine the individual based on its fitness
        new_individual = self.refine_individual(individual, new_individual, alpha)
        
        # Update the individual
        individual = new_individual
        
        return individual

    def refine_individual(self, individual, fitness, alpha=0.1):
        """
        Refines the individual based on its fitness.
        
        Args:
        individual (list): The current individual.
        fitness (float): The individual's fitness.
        alpha (float, optional): The perturbation strength. Defaults to 0.1.
        
        Returns:
        list: The refined individual.
        """
        # Generate a new individual by perturbing the current individual
        new_individual = self.perturb(individual, self.bounds)
        
        # Evaluate the new individual using the black box function
        new_fitness = self.func(new_individual)
        
        # Update the individual's fitness
        individual = [self.bounds[0] + np.random.uniform(-1, 1) * (self.bounds[1] - self.bounds[0]) for _ in range(self.dim)]
        individual = [max(bounds[i], min(individual[i], bounds[i])) for i in range(self.dim)]
        individual = [self.bounds[0] + alpha * (fitness - individual[0]) for _ in range(self.dim)]
        
        # Ensure the new individual is within the bounds
        individual = [max(bounds[i], min(individual[i], bounds[i])) for i in range(self.dim)]
        
        return individual

# Description: Black Box Optimization using MetaHeuristic Algorithm
# Code: 