import numpy as np
from scipy.optimize import minimize

class MetaHeuristic:
    """
    A metaheuristic algorithm for solving black box optimization problems.
    
    The algorithm uses a combination of local search, genetic algorithm, and evolutionary optimization to find the optimal solution.
    
    Attributes:
    budget (int): The maximum number of function evaluations allowed.
    dim (int): The dimensionality of the search space.
    func (function): The black box function to optimize.
    search_space (list): The range of the search space.
    bounds (list): The bounds of the search space.
    population (list): The current population of individuals.
    """

    def __init__(self, budget, dim):
        """
        Initializes the MetaHeuristic algorithm.
        
        Args:
        budget (int): The maximum number of function evaluations allowed.
        dim (int): The dimensionality of the search space.
        """
        self.budget = budget
        self.dim = dim
        self.func = None
        self.search_space = None
        self.bounds = None
        self.population = None

    def __call__(self, func):
        """
        Optimizes the black box function using MetaHeuristic.
        
        Args:
        func (function): The black box function to optimize.
        
        Returns:
        tuple: A tuple containing the optimal solution and its cost.
        """
        if self.func is None:
            raise ValueError("The black box function must be initialized before calling this method.")
        
        # Initialize the search space
        self.search_space = [self.bounds] * self.dim
        self.bounds = [(-5.0, 5.0)] * self.dim
        
        # Initialize the optimal solution and its cost
        opt_solution = None
        opt_cost = float('inf')
        
        # Perform local search
        for _ in range(self.budget):
            # Generate a new solution by perturbing the current solution
            new_solution = self.perturb(self.search_space, self.bounds)
            
            # Evaluate the new solution using the black box function
            new_cost = self.func(new_solution)
            
            # Update the optimal solution and its cost if necessary
            if new_cost < opt_cost:
                opt_solution = new_solution
                opt_cost = new_cost
        
        # Return the optimal solution and its cost
        return opt_solution, opt_cost

    def perturb(self, search_space, bounds):
        """
        Generates a new solution by perturbing the current solution.
        
        Args:
        search_space (list): The current search space.
        bounds (list): The current bounds of the search space.
        
        Returns:
        list: A new solution generated by perturbing the current solution.
        """
        # Generate a new solution by randomly perturbing the current solution
        new_solution = [self.bounds[0] + np.random.uniform(-1, 1) * (self.bounds[1] - self.bounds[0]) for _ in range(self.dim)]
        
        # Ensure the new solution is within the bounds
        new_solution = [max(bounds[i], min(new_solution[i], bounds[i])) for i in range(self.dim)]
        
        return new_solution

    def evolve_population(self, population, func):
        """
        Evolves the population using genetic algorithm.
        
        Args:
        population (list): The current population of individuals.
        func (function): The black box function to optimize.
        
        Returns:
        list: The evolved population.
        """
        # Initialize the population with random solutions
        population = [self.evaluate_fitness(np.random.uniform(-5.0, 5.0), func) for _ in range(100)]
        
        # Evolve the population
        for _ in range(100):
            # Select the fittest individuals
            fittest_individuals = population[np.argsort(population)]
            
            # Create a new population by perturbing the fittest individuals
            new_population = [self.perturb(fittest_individual, self.bounds) for fittest_individual in fittest_individuals]
            
            # Evaluate the new population
            new_population = [self.evaluate_fitness(individual, func) for individual in new_population]
            
            # Replace the old population with the new population
            population = new_population
        
        return population

    def genetic_algorithm(self, func, bounds, population_size, mutation_rate):
        """
        Evolves the population using genetic algorithm.
        
        Args:
        func (function): The black box function to optimize.
        bounds (list): The bounds of the search space.
        population_size (int): The size of the population.
        mutation_rate (float): The mutation rate.
        
        Returns:
        list: The evolved population.
        """
        # Initialize the population with random solutions
        population = [self.evaluate_fitness(np.random.uniform(-5.0, 5.0), func) for _ in range(population_size)]
        
        # Evolve the population
        for _ in range(100):
            # Select the fittest individuals
            fittest_individuals = population[np.argsort(population)]
            
            # Create a new population by perturbing the fittest individuals
            new_population = [self.perturb(fittest_individual, bounds) for fittest_individual in fittest_individuals]
            
            # Evaluate the new population
            new_population = [self.evaluate_fitness(individual, func) for individual in new_population]
            
            # Replace the old population with the new population
            population = new_population
        
        return population

# Description: Adaptive Black Box Optimization using Evolutionary Algorithm
# Code: 