import numpy as np
from scipy.optimize import minimize
import random

class MetaHeuristic:
    """
    A metaheuristic algorithm for solving black box optimization problems.
    
    The algorithm uses a combination of local search and gradient-based optimization to find the optimal solution.
    It also incorporates a refinement strategy to improve the solution's performance.
    
    Attributes:
    budget (int): The maximum number of function evaluations allowed.
    dim (int): The dimensionality of the search space.
    func (function): The black box function to optimize.
    search_space (list): The range of the search space.
    bounds (list): The bounds of the search space.
    refinement_strategy (list): The refinement strategy to use.
    """

    def __init__(self, budget, dim):
        """
        Initializes the MetaHeuristic algorithm.
        
        Args:
        budget (int): The maximum number of function evaluations allowed.
        dim (int): The dimensionality of the search space.
        """
        self.budget = budget
        self.dim = dim
        self.func = None
        self.search_space = None
        self.bounds = None
        self.refinement_strategy = None

    def __call__(self, func):
        """
        Optimizes the black box function using MetaHeuristic.
        
        Args:
        func (function): The black box function to optimize.
        
        Returns:
        tuple: A tuple containing the optimal solution and its cost.
        """
        if self.func is None:
            raise ValueError("The black box function must be initialized before calling this method.")
        
        # Initialize the search space
        self.search_space = [self.bounds] * self.dim
        self.bounds = [(-5.0, 5.0)] * self.dim
        
        # Initialize the optimal solution and its cost
        opt_solution = None
        opt_cost = float('inf')
        
        # Perform local search
        for _ in range(self.budget):
            # Generate a new solution by perturbing the current solution
            new_solution = self.perturb(self.search_space, self.bounds)
            
            # Evaluate the new solution using the black box function
            new_cost = self.func(new_solution)
            
            # Update the optimal solution and its cost if necessary
            if new_cost < opt_cost:
                opt_solution = new_solution
                opt_cost = new_cost
        
        # Return the optimal solution and its cost
        return opt_solution, opt_cost

    def perturb(self, search_space, bounds):
        """
        Generates a new solution by perturbing the current solution.
        
        Args:
        search_space (list): The current search space.
        bounds (list): The current bounds of the search space.
        
        Returns:
        list: A new solution generated by perturbing the current solution.
        """
        # Generate a new solution by randomly perturbing the current solution
        new_solution = [self.bounds[0] + np.random.uniform(-1, 1) * (self.bounds[1] - self.bounds[0]) for _ in range(self.dim)]
        
        # Ensure the new solution is within the bounds
        new_solution = [max(bounds[i], min(new_solution[i], bounds[i])) for i in range(self.dim)]
        
        return new_solution

    def refine(self, new_individual):
        """
        Refines the solution using the refinement strategy.
        
        Args:
        new_individual (list): The new solution to refine.
        
        Returns:
        list: The refined solution.
        """
        # Select a random individual from the search space
        selected_individual = random.choice(self.search_space)
        
        # Evaluate the selected individual using the black box function
        selected_cost = self.func(selected_individual)
        
        # Refine the solution based on the selected individual and its cost
        if selected_cost < self.func(self.bounds):
            return selected_individual
        else:
            return self.perturb(self.search_space, self.bounds)

# Description: Black Box Optimization using MetaHeuristic Algorithm with Refinement Strategy
# Code: 
# ```python
# Black Box Optimization using MetaHeuristic Algorithm with Refinement Strategy
# ```python
meta_heuristic = MetaHeuristic(10, 5)
func = lambda x: np.sin(x)
opt_solution, opt_cost = meta_heuristic(func, 5)
refined_solution = meta_heuristic.refine(opt_solution)
opt_solution, opt_cost = meta_heuristic(func, 5)
print(f"Optimal solution: {opt_solution}, Optimal cost: {opt_cost}")