import numpy as np
from scipy.optimize import minimize

class MetaHeuristic:
    """
    A metaheuristic algorithm for solving black box optimization problems.
    
    The algorithm uses a combination of local search and gradient-based optimization to find the optimal solution.
    """
    
    def __init__(self, budget, dim):
        """
        Initializes the MetaHeuristic algorithm.
        
        Args:
        budget (int): The maximum number of function evaluations allowed.
        dim (int): The dimensionality of the search space.
        """
        self.budget = budget
        self.dim = dim
        self.func = None
        self.search_space = None
        self.bounds = None

    def __call__(self, func):
        """
        Optimizes the black box function using MetaHeuristic.
        
        Args:
        func (function): The black box function to optimize.
        
        Returns:
        tuple: A tuple containing the optimal solution and its cost.
        """
        if self.func is None:
            raise ValueError("The black box function must be initialized before calling this method.")
        
        # Initialize the search space
        self.search_space = [self.bounds] * self.dim
        self.bounds = [(-5.0, 5.0)] * self.dim
        
        # Initialize the optimal solution and its cost
        opt_solution = None
        opt_cost = float('inf')
        
        # Perform local search
        for _ in range(self.budget):
            # Generate a new solution by perturbing the current solution
            new_solution = self.perturb(self.search_space, self.bounds)
            
            # Evaluate the new solution using the black box function
            new_cost = self.func(new_solution)
            
            # Update the optimal solution and its cost if necessary
            if new_cost < opt_cost:
                opt_solution = new_solution
                opt_cost = new_cost
        
        # Return the optimal solution and its cost
        return opt_solution, opt_cost

    def perturb(self, search_space, bounds):
        """
        Generates a new solution by perturbing the current solution.
        
        Args:
        search_space (list): The current search space.
        bounds (list): The current bounds of the search space.
        
        Returns:
        list: A new solution generated by perturbing the current solution.
        """
        # Generate a new solution by randomly perturbing the current solution
        new_solution = [self.bounds[0] + np.random.uniform(-1, 1) * (self.bounds[1] - self.bounds[0]) for _ in range(self.dim)]
        
        # Ensure the new solution is within the bounds
        new_solution = [max(bounds[i], min(new_solution[i], bounds[i])) for i in range(self.dim)]
        
        return new_solution

    def optimize(self, func, initial_solution, num_iterations):
        """
        Optimizes the black box function using the MetaHeuristic algorithm.
        
        Args:
        func (function): The black box function to optimize.
        initial_solution (list): The initial solution to start the optimization process with.
        num_iterations (int): The number of iterations to perform.
        
        Returns:
        tuple: A tuple containing the optimal solution and its cost.
        """
        # Initialize the population
        population = initial_solution
        
        # Perform the specified number of iterations
        for _ in range(num_iterations):
            # Evaluate the fitness of each individual in the population
            fitness = [self.func(individual) for individual in population]
            
            # Select the fittest individuals
            fittest_individuals = np.argsort(fitness)[::-1]
            
            # Create a new population by perturbing the fittest individuals
            new_population = [self.perturb(population[i], self.bounds) for i in fittest_individuals]
            
            # Replace the old population with the new population
            population = new_population
        
        # Return the fittest individual in the final population
        return population[0], fitness[0]

# Example usage
if __name__ == "__main__":
    # Define the black box function
    def func(x):
        return np.sum(x**2)
    
    # Initialize the MetaHeuristic algorithm
    metaheuristic = MetaHeuristic(10, 5)
    
    # Optimize the black box function using the MetaHeuristic algorithm
    optimal_solution, optimal_cost = metaheuristic.optimize(func, [-10, 10], 1000)
    
    # Print the result
    print("Optimal solution:", optimal_solution)
    print("Optimal cost:", optimal_cost)