import numpy as np
from scipy.optimize import minimize

class MetaHeuristic:
    """
    A metaheuristic algorithm for solving black box optimization problems.
    
    The algorithm uses a combination of local search, evolutionary strategies, and gradient-based optimization to find the optimal solution.
    
    Attributes:
    budget (int): The maximum number of function evaluations allowed.
    dim (int): The dimensionality of the search space.
    func (function): The black box function to optimize.
    search_space (list): The range of the search space.
    bounds (list): The bounds of the search space.
    """

    def __init__(self, budget, dim):
        """
        Initializes the MetaHeuristic algorithm.
        
        Args:
        budget (int): The maximum number of function evaluations allowed.
        dim (int): The dimensionality of the search space.
        """
        self.budget = budget
        self.dim = dim
        self.func = None
        self.search_space = None
        self.bounds = None

    def __call__(self, func):
        """
        Optimizes the black box function using MetaHeuristic.
        
        Args:
        func (function): The black box function to optimize.
        
        Returns:
        tuple: A tuple containing the optimal solution and its cost.
        """
        if self.func is None:
            raise ValueError("The black box function must be initialized before calling this method.")
        
        # Initialize the search space
        self.search_space = [self.bounds] * self.dim
        self.bounds = [(-5.0, 5.0)] * self.dim
        
        # Initialize the optimal solution and its cost
        opt_solution = None
        opt_cost = float('inf')
        
        # Perform local search
        for _ in range(self.budget):
            # Generate a new solution by perturbing the current solution
            new_solution = self.perturb(self.search_space, self.bounds)
            
            # Evaluate the new solution using the black box function
            new_cost = self.func(new_solution)
            
            # Update the optimal solution and its cost if necessary
            if new_cost < opt_cost:
                opt_solution = new_solution
                opt_cost = new_cost
        
        # Return the optimal solution and its cost
        return opt_solution, opt_cost

    def perturb(self, search_space, bounds):
        """
        Generates a new solution by perturbing the current solution.
        
        Args:
        search_space (list): The current search space.
        bounds (list): The current bounds of the search space.
        
        Returns:
        list: A new solution generated by perturbing the current solution.
        """
        # Generate a new solution by randomly perturbing the current solution
        new_solution = [self.bounds[0] + np.random.uniform(-1, 1) * (self.bounds[1] - self.bounds[0]) for _ in range(self.dim)]
        
        # Ensure the new solution is within the bounds
        new_solution = [max(bounds[i], min(new_solution[i], bounds[i])) for i in range(self.dim)]
        
        return new_solution

    def evolve(self, func, budget):
        """
        Evolves the MetaHeuristic using evolutionary strategies.
        
        Args:
        func (function): The black box function to optimize.
        budget (int): The maximum number of function evaluations allowed.
        
        Returns:
        tuple: A tuple containing the optimal solution and its cost.
        """
        # Initialize the population
        population = self.generate_population(func, budget)
        
        # Evolve the population
        for _ in range(budget):
            # Select the fittest individual
            fittest_individual = self.select_fittest(population)
            
            # Perform local search on the fittest individual
            new_individual = self.perturb(self.search_space, self.bounds)
            new_cost = self.func(new_individual)
            
            # Update the fittest individual and its cost
            if new_cost < fittest_individual[1]:
                fittest_individual = (new_individual, new_cost)
        
        # Return the fittest individual and its cost
        return fittest_individual

    def generate_population(self, func, budget):
        """
        Generates a population of individuals using evolutionary strategies.
        
        Args:
        func (function): The black box function to optimize.
        budget (int): The maximum number of function evaluations allowed.
        
        Returns:
        list: A list of individuals in the population.
        """
        # Initialize the population
        population = []
        
        # Generate a population of individuals
        for _ in range(budget):
            # Generate an individual by perturbing the current solution
            individual = self.perturb(self.search_space, self.bounds)
            
            # Evaluate the individual using the black box function
            individual_cost = self.func(individual)
            
            # Add the individual to the population
            population.append((individual, individual_cost))
        
        return population

    def select_fittest(self, population):
        """
        Selects the fittest individual from the population.
        
        Args:
        population (list): A list of individuals in the population.
        
        Returns:
        tuple: The fittest individual and its cost.
        """
        # Select the fittest individual using tournament selection
        fittest_individual = max(population, key=lambda x: x[1])
        
        return fittest_individual

# Description: Adaptive Black Box Optimization using Evolutionary Strategies
# Code: 